import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const profile = body.profile;

    // Very basic rule-based recommendation for demo purposes.
    const name = profile?.name || 'Student';
    const grade = profile?.grades || 'N/A';
    const majors = (profile?.intendedMajors || []).slice(0, 3).join(', ') || 'Undeclared';

    const recommendation = `Hi ${name}! Based on your current reported grade of ${grade}% and interest in ${majors}, here are 3 colleges you might consider (demo):\n\n1) Demo University — Strong ${majors} program, moderate acceptance rate.\n2) Example Institute — Good industry ties and placement opportunities.\n3) Sample College — Strong extracurricular support and campus life.\n\nImmediate next steps:\n- Improve subject grades relevant to your chosen majors.\n- Take standardized tests as required for your target country.\n- Research scholarship & financial aid options.\n\n(Disclaimer: This is a demo AI response generated by the College Pathfinder demo API.)`;

    return NextResponse.json({ recommendation });
  } catch (err) {
    return NextResponse.json({ recommendation: 'Failed to generate recommendation.' }, { status: 500 });
  }
}
